version: '3.8'
services:
  frontend:
    build:
      context: ../cptl_gains_frontend
      dockerfile: Dockerfile
    ports:
      - "8100:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../cptl_gains_backend
      dockerfile: Dockerfile
    ports:
      - "8300:8080" 